require('globals')
require('general')
require('mappings')
require('plugins')
require('statusline')

require('config/autopairs')
require('config/bufferline')
require('config/colorizer')
require('config/cmp')
require('config/crates')
require('config/dap-ui')
require('config/git-signs')
require('config/indent-blankline')
require('config/lsp-config')
require('config/rust-tools')
require('config/symbols-outline')
require('config/telescope')
require('config/tree-sitter')

